# This is a basic workflow to help you get started with Actions

name: Flutter Release Tag Generation

# Controls when the workflow will run
on:
  repository_dispatch:
    types: [Flutter Release Tag Generation]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4

      - name: Create Android Release Tag
        run: |
          flutter_branch=${{ github.event.client_payload.flutter_branch }}
          echo "Creating Android release tag for branch: $flutter_branch"
